server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: h2

  datasource:
    embedded-database-connection: h2
    name: pre
  h2:
    console:
      enabled: true
      path: /pre-db
logging:
  level:
    #org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
