server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8
  error:
    whitelabel:
      enabled: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: h2
  datasource:
    embedded-database-connection: h2
    name: pre
    url: jdbc:h2:mem:pre_test
  h2:

    console:
      enabled: true
      path: /pre-db
logging:
  level:
    #org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
