server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  datasource:
    embedded-database-connection: h2
    name: pre
  h2:
    console:
      enabled: true
      path: /pre-db

